import { FC } from 'react';

export const Footer: FC = () => {
  return (
    <footer
      className="w-full max-md:pb-4 py-1 text-base-content/70 text-xs text-center"
      tabIndex={0}
      aria-description="Statement"
    >
      <span>The content is generated by AI. It may be inaccurate.</span>
    </footer>
  );
};
